# Generated by Django 3.0.6 on 2023-08-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='descricao')),
                ('required', models.BooleanField(default=False, help_text='Marque para deixar o campo obrigatório', verbose_name='obrigatorio')),
                ('enabled', models.BooleanField(default=False, help_text='marque para manter que o campo apareça no formulario de envio', verbose_name='habilitado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='descricao')),
            ],
            options={
                'verbose_name': 'Status da proposta',
            },
        ),
    ]
