# Generated by Django 3.0.6 on 2023-08-26 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_financialproposal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialproposal',
            options={'verbose_name': 'Proposta financeira', 'verbose_name_plural': 'Propostas financeiras'},
        ),
        migrations.AlterModelOptions(
            name='proposalfields',
            options={'verbose_name': 'Campo da proposta', 'verbose_name_plural': 'Campos da proposta'},
        ),
    ]
