# Generated by Django 3.0.6 on 2023-08-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_auto_20230826_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalfields',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number')], max_length=50, null=True),
        ),
    ]
