# Generated by Django 3.0.6 on 2023-08-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('financial', '0004_proposalfields_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialproposal',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='person.Person'),
        ),
        migrations.AddField(
            model_name='financialproposal',
            name='proposal_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
